[package]
name = "dump-pmtiles-labels"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.34", features = ["derive"] }
flate2 = "1.1.0"
indicatif = "0.17.11"
nom = "8.0.0"
prost = "0.13.5"
prost-types = "0.13.5"

[build-dependencies]
prost-build = "0.13.5"
